import io
from typing import List, Dict
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors

def generate_case_summary_pdf(fir: Dict, persons: List[Dict]) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    flowables = []

    flowables.append(Paragraph(f"Case Summary: FIR #{fir['fir_id']}", styles['Title']))
    flowables.append(Spacer(1, 0.2 * inch))
    flowables.append(Paragraph(f"<b>Date:</b> {fir['date']}", styles['Normal']))
    flowables.append(Paragraph(f"<b>Crime Type:</b> {fir['crime_type']}", styles['Normal']))
    flowables.append(Paragraph(f"<b>Location:</b> {fir['location']}", styles['Normal']))
    flowables.append(Paragraph(f"<b>District:</b> {fir['district']}", styles['Normal']))
    flowables.append(Paragraph(f"<b>Status:</b> {fir['status']}", styles['Normal']))
    flowables.append(Spacer(1, 0.15 * inch))
    flowables.append(Paragraph(f"<b>Description:</b>", styles['Heading2']))
    flowables.append(Paragraph(fir['description'], styles['Normal']))
    flowables.append(Spacer(1, 0.15 * inch))

    if persons:
        flowables.append(Paragraph("Involved Persons:", styles['Heading2']))
        table_data = [["Name", "Role", "Age", "Gender", "Address"]]
        for p in persons:
            table_data.append([p.get('person_name', p.get('name', '')), p['role'], str(p.get('age', '')), p.get('gender', ''), p.get('address', '')])
        t = Table(table_data, colWidths=[1.2*inch, 0.8*inch, 0.5*inch, 0.6*inch, 1.8*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        flowables.append(t)
        flowables.append(Spacer(1, 0.15 * inch))

    flowables.append(Paragraph("Generated by KSP Crime Intelligence Copilot", styles['Normal']))
    doc.build(flowables)
    buffer.seek(0)
    return buffer

def generate_chat_pdf(conversation: List[Dict], title: str = "Chat Export") -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    flowables = []

    flowables.append(Paragraph(title, styles['Title']))
    flowables.append(Spacer(1, 0.2 * inch))

    for msg in conversation:
        role = msg.get('role', 'User')
        content = msg.get('content', '')
        if role == 'user':
            flowables.append(Paragraph(f"<b>User:</b> {content}", styles['Normal']))
        else:
            flowables.append(Paragraph(f"<b>Copilot:</b> {content}", styles['Normal']))
        flowables.append(Spacer(1, 0.1 * inch))

    flowables.append(Spacer(1, 0.3 * inch))
    flowables.append(Paragraph("— End of Report —", styles['Normal']))
    doc.build(flowables)
    buffer.seek(0)
    return buffer
